[test]
levels = ["syntax", "javascript", "install", "execution"]
publish = true

[test.workflows]
cpu = []
cuda = ["!mesh_audit"]

[test.platforms]
platforms = ["linux_cuda", "windows_cuda", "windows_portable_cuda", "windows_desktop_cuda"]
