# SPDX-License-Identifier: MIT
# GPU-isolated nodes for TRELLIS.2 inference

from .nodes_inference import (
    NODE_CLASS_MAPPINGS as INFERENCE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as INFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes_video import (
    NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **INFERENCE_NODE_CLASS_MAPPINGS,
    **VIDEO_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **INFERENCE_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
